print('\033[31mOlá, mundo!\033[m') #USANDO O PRINT PARA FAZER UMA MENSAGEM APARECER NA TELA
msg = '\033[34mHello, world!\033[m' #CRIANDO UMA VARIAVEL COM A MENSAGEM
print(msg) #EXIBINDO A MENSAGEM DA VARIAVEL COM O PRINT
